<?php

// Timezone
date_default_timezone_set('America/Toronto');
// Get prev and next month
if (isset($_GET['ym'])) {
    $ym = $_GET['ym'];
} else {
    // current month
    $ym = date ('Y-m');
}

// Check format
$timestamp = strtotime($ym, "-01");
if($timestamp === false){
    $timestamp = time();
}

// Today
$today = date('Y-m-d', time());

// For H3 title
$html_title = date('Y / m', $timestamp);

// Prev and next month link
$prev = date('Y-m', mktime(0,0,0, date('m', $timestamp)-1, 1, date('Y', $timestamp)));
$next = date('Y-m', mktime(0,0,0, date('m', $timestamp)+1, 1, date('Y', $timestamp)));

// Number of day in a month
$day_count = date('t', $timestamp);

// Day (Sun-Sat)
$str = date('w', mktime(0,0,0, date('m', $timestamp), 1, date('Y', $timestamp)));

// Create Calendar
$weeks = array();
$week = '';

// Empty Cell
$week .= str_repeat('<td></td>', $str);
for ( $day = 1; $day <= $day_count; $day++, $str++){
    $date = $ym. '-'. $day;

    if ($today == $date){
        $week .= '<td class="today">' . $day;
    } else {
        $week .= '<td>' . $day;
    }
    $week .= '</td>';

    // End of the week/month
    if ($str % 7 == 6 || $day == $day_count){
        if($day == $day_count){
            //empty cell
            $week .= str_repeat('<td></td>', 6 - ($str % 7));
        }

        $weeks[] = '<tr>' . $week . '</tr>';

        //Prepare for new week
        $week = '';
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Calendar</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
    <style>
        th {
            height: 10px;
            width: 10px;
            text-align: center;
            font-weight: 600;
        }
        td {
            height: 10px;
            width: 10px;
        }
        .today {
            background: mediumpurple;
            color: purple;
        }
        th:nth-of-type(1), td:nth-of-type(1){
            color: red;
        }
    </style>
</head>
<body>
    <div class="container">
        <h4>
            <?php echo $html_title; ?>
            </h4>
        <br>
        <table class="table table-bordered">
            <tr>
                <th>S</th>
                <th>M</th>
                <th>T</th>
                <th>W</th>
                <th>T</th>
                <th>F</th>
                <th>S</th>
            </tr>
            <?php
                foreach ($weeks as $week){
                    echo $week;
                }
            ?>
        </table>
    </div>
</body>
</html>
