<?php
session_start();

?>

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">
    <title>PURPLE BANANA</title>
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
    <!-- Custom styles for this template -->
    <link rel="stylesheet" type="text/css" href="style.css">

</head>

<body>
<div id="wrap">
    <div id="main">
        <nav class="navbar navbar-expand-md fixed-top navbar-dark bg-dark">
            <h1 class="navbar-brand">PURPLE BANANA</h1>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="?page=home">Dashboard<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item  active">
                        <a class="nav-link" href="?page=progressForTheMonth">Progress</a>
                    </li>
                    <li class="nav-item  active">
                        <a class="nav-link " href="?page=profiles">My Profile</a>
                    </li>
                </ul>
                <form action="?page=logout.inc" class="nav-logout" method="POST">
                    <button class="btn" type="submit" name="submit">LOGOUT</button>
                </form><!--logout-->
            </div>
        </nav> <!--end navigator-->
