<?php
session_start();
?>

<html>
<head>
    <title>PURPLE BANANA</title>
    <link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>
    <div class="login-wrapper">
        <form>
            <h1>PURPLE BANANA</h1>
            <a href="?page=signup" id="button">SIGN UP</a>
            <a href="?page=login" id="button">LOGIN</a>
        </form>
    </div>
</body>
</html>


