<?php
session_start();
?>


<html>
<head>
    <title>PURPLE BANANA</title>
    <link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>
<section class="main-container">
    <h2 id="login">LOGIN</h2>
    <form class="login-form" action="?page=login.inc" method="POST">
        <input type="text" name="uid" placeholder="Username">
        <input type="password" name="pwd" placeholder="Password">
        <button type="submit" name="submit">Login</button>
    </form>
</section>
</body>
</html>
