<?php session_start(); ?>

<html>
<head>
    <title>PURPLE BANANA</title>
    <link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>
<section class="main-container">
    <h2 id="signup">SIGNUP</h2>
        <form class="signup-form" action="?page=signup.inc" method="POST">
            <input type="text" name="first" placeholder="Firstname">
            <input type="text" name="last" placeholder="Lastname">
            <input type="text" name="email" placeholder="E-mail">
            <input type="text" name="uid" placeholder="Username">
            <input type="password" name="pwd" placeholder="Password">
            <button type="submit" name="submit">Signup</button>
        </form>
</section>
</body>
</html>
